good = {...
	'aaa';...
};
bad = {...
	'daisy5_20190404', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'daisy5_20190411', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'daisy5_20190423', 'openNEV', 'Index in position 1 exceeds array bounds (must not exceed 20).';...
	'daisy5_20190423', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'daisy5_20190424', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'daisy5_20190404', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'daisy5_20190404', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'daisy5_20190404', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'daisy5_20190404', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'daisy5_20190404', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'daisy5_20190404', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'daisy5_20190404', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'daisy5_20190404', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'daisy5_20190404', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'daisy5_20190404', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'daisy5_20190404', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
};