%% Fill in missing bootstrap results (lick, reach vs. baseline)
sel = c.hasPress(:) & isnan(boot.press.h);
[boot.press.h(sel), boot.press.muDiffCI(sel, :), boot.press.muDiffObs(sel)] = bootstrapMoveResponse( ...
    eu(sel), 'press', nboot=p.nboot, alpha=p.bootAlpha, withReplacement=false, oneSided=false, ...
    responseWindow=p.responseWindowPress);

sel = c.hasLick(:) & isnan(boot.lick.h);
[boot.lick.h(sel), boot.lick.muDiffCI(sel, :), boot.lick.muDiffObs(sel)] = bootstrapMoveResponse( ...
    eu(sel), 'lick', nboot=p.nboot, alpha=p.bootAlpha, withReplacement=false, oneSided=false, ...
    responseWindow=p.responseWindowLick);

save('boot_20241024_perimovement_0.3_0.mat', 'boot', 'c', 'p')